language: en
commands:
  save: save
  remove: remove
  info: info
  list: list
  menu: menu
  reload: reload

descriptions:
  en:
    save: "Save the current WorldEdit selection with the given name."
    remove: "Delete the specified region."
    info: "Show region coordinates and number of players inside."
    list: "List all saved regions. If a name is specified, shows placeholder info."
    menu: "Show descriptions for all commands."
    reload: "Reload plugin configuration."
  tr:
    save: "Ge\u00E7erli WorldEdit se\u00E7imini verilen isimle kaydeder."
    remove: "Belirtilen b\u00F6lgeyi siler."
    info: "B\u00F6lge koordinatlar\u0131n\u0131 ve i\u00E7indeki oyuncu say\u0131s\u0131n\u0131 g\u00F6sterir."
    list: "Kay\u0131tl\u0131 t\u00FCm b\u00F6lgeleri listeler. \u0130sim belirtilirse placeholder bilgisini g\u00F6sterir."
    menu: "T\u00FCm komutlar\u0131n a\u00E7\u0131klamalar\u0131n\u0131 g\u00F6sterir."
    reload: "Eklentinin yap\u0131land\u0131rmas\u0131n\u0131 yeniden y\u00FCkler."

messages:
  en:
    onlyPlayers: "&cOnly players can use this command."
    noPermission: "&cYou must be OP to use this command."
    needSelection: "&cYou must make a WorldEdit selection first."
    regionSaved: "&aRegion &e%name% &asuccessfully saved."
    usageSave: "&eUsage: /%cmd% %save% <name>"
    regionRemoved: "&aRegion &e%name% &aremoved."
    regionNotFound: "&cRegion not found."
    regionHeader: "&6Region &e%name%&6:"
    pos1: "&7Pos1: &f%pos1%"
    pos2: "&7Pos2: &f%pos2%"
    playersInside: "&7Players inside: &f%count%"
    regionsHeader: "&6Saved Regions:"
    regionEntry: "&e- %name%"
    placeholderInfo: "&aPlaceholder for %name%: &e%placeholder%"
    menuHeader: "&6[ Area Commands ]"
    menuEntry: "&e/%cmd% %sub%%usage% &7- %desc%"
    reloaded: "&aConfiguration reloaded."
  tr:
    onlyPlayers: "&cBu komutu sadece oyuncular kullanabilir."
    noPermission: "&cBu komutu kullanmak i\u00E7in OP olmal\u0131s\u0131n\u0131z."
    needSelection: "&c\u00D6nce bir WorldEdit se\u00E7imi yapmal\u0131s\u0131n\u0131z."
    regionSaved: "&aB\u00F6lge &e%name% &aba\u015Far\u0131yla kaydedildi."
    usageSave: "&eKullan\u0131m: /%cmd% %save% <isim>"
    regionRemoved: "&aB\u00F6lge &e%name% &asilindi."
    regionNotFound: "&cB\u00F6lge bulunamad\u0131."
    regionHeader: "&6B\u00F6lge &e%name%&6:"
    pos1: "&7Pos1: &f%pos1%"
    pos2: "&7Pos2: &f%pos2%"
    playersInside: "&7\u0130\u00E7erideki oyuncu say\u0131s\u0131: &f%count%"
    regionsHeader: "&6Kay\u0131tl\u0131 B\u00F6lgeler:"
    regionEntry: "&e- %name%"
    placeholderInfo: "&a%name% &7i\u00E7in kullanabilece\u011Fin placeholder: &e%placeholder%"
    menuHeader: "&6[ B\u00F6lge Komutlar\u0131 ]"
    menuEntry: "&e/%cmd% %sub%%usage% &7- %desc%"
    reloaded: "&aYap\u0131land\u0131rma yeniden y\u00FCklendi."
