commands:
  base: area
  save: save
  remove: remove
  info: info
  list: list
  menu: menu
  reload: reload

descriptions:
  save: "Geçerli WorldEdit seçimini verilen isimle kaydeder."
  remove: "Belirtilen bölgeyi siler."
  info: "Bölge koordinatlarını ve içindeki oyuncu sayısını gösterir."
  list: "Kayıtlı tüm bölgeleri listeler."
  menu: "Tüm komutların açıklamalarını gösterir."
  reload: "Eklentinin yapılandırmasını yeniden yükler."

messages:
  onlyPlayers: "&cBu komutu sadece oyuncular kullanabilir."
  needSelection: "&cÖnce bir WorldEdit seçimi yapmalısınız."
  regionSaved: "&aBölge &e%name% &abaşarıyla kaydedildi."
  usageSave: "&eKullanım: /%cmd% %save% <isim>"
  regionRemoved: "&aBölge &e%name% &asilindi."
  regionNotFound: "&cBölge bulunamadı."
  regionHeader: "&6Bölge &e%name%&6:"
  pos1: "&7Pos1: &f%pos1%"
  pos2: "&7Pos2: &f%pos2%"
  playersInside: "&7İçerideki oyuncu sayısı: &f%count%"
  regionsHeader: "&6Kayıtlı Bölgeler:"
  regionEntry: "&e- %name%"
  menuHeader: "&6[ Bölge Komutları ]"
  menuEntry: "&e/%cmd% %sub%%usage% &7- %desc%"
  reloaded: "&aYapılandırma yeniden yüklendi."
