name: AreaPlayerControl
main: com.example.areaplayercontrol.AreaPlayerControl
version: 1.0
api-version: '1.21'
commands:
  areaplayercontrol:
    description: Manage areas
    usage: /<command> <save|remove|info|list|menu|reload> [name]
