name: AreaPlayerControl
main: com.example.areaplayercontrol.AreaPlayerControl
version: 1.0
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  areaplayercontrol:
    description: Manage areas
    usage: /<command> <save|remove|info|list|menu|reload> [name]
    aliases: [area]
    permission: areaplayercontrol.admin
    permission-message: "&cYou do not have permission to use this command."

permissions:
  areaplayercontrol.admin:
    description: Allows use of AreaPlayerControl commands
    default: op
