name: AreaPlayerControl
main: com.example.areaplayercontrol.AreaPlayerControl
version: 1.0
# Target API version 1.20 for compatibility with 1.20.x servers
api-version: '1.20'
softdepend: [PlaceholderAPI]
commands:
  areaplayercontrol:
    description: Manage areas
    usage: /<command> <save|remove|info|list|menu|reload> [name]
    aliases: [area]
